"""Alembic environment, wired to the app's settings and ORM metadata.

The database URL comes from the app config (``DATABASE_URL`` in ``.env``) rather
than being hardcoded in ``alembic.ini`` — so migrations always target the same
database the app uses (SQLite locally, Postgres in the cloud). ``target_metadata``
is the app's ``Base.metadata`` so ``alembic revision --autogenerate`` can diff the
models against the live schema.
"""
import os
import sys
from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool

from alembic import context

# Make the backend package importable regardless of the working directory.
BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if BACKEND_DIR not in sys.path:
    sys.path.insert(0, BACKEND_DIR)

from app.config import get_settings  # noqa: E402
from app.crypto import EncryptedString  # noqa: E402
from app.database import Base  # noqa: E402
from app import models  # noqa: E402,F401  (import registers all tables on Base.metadata)

config = context.config

# Inject the app's database URL (config file leaves sqlalchemy.url blank).
config.set_main_option("sqlalchemy.url", get_settings().database_url)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def _is_sqlite(url: str) -> bool:
    return url.startswith("sqlite")


def render_item(type_, obj, autogen_context):
    """Emit a self-contained import for the custom EncryptedString column type so
    autogenerated migrations that touch encrypted columns run without hand-editing."""
    if type_ == "type" and isinstance(obj, EncryptedString):
        autogen_context.imports.add("import app.crypto")
        return "app.crypto.EncryptedString()"
    return False


def run_migrations_offline() -> None:
    """Emit SQL to stdout without a DBAPI connection."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        render_item=render_item,
        # Batch mode lets SQLite emulate ALTER TABLE for future migrations.
        render_as_batch=_is_sqlite(url or ""),
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations against a live connection."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            render_item=render_item,
            render_as_batch=connection.dialect.name == "sqlite",
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
