"""initial schema

Revision ID: 387d4ed0df29
Revises: 
Create Date: 2026-08-24 17:24:36.183518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.crypto  # EncryptedString custom column type


# revision identifiers, used by Alembic.
revision: str = '387d4ed0df29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_amount', sa.Float(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('expected_annual_return', sa.Float(), nullable=False),
    sa.Column('monthly_contribution', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plaid_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('access_token', app.crypto.EncryptedString(), nullable=False),
    sa.Column('institution_name', sa.String(), nullable=True),
    sa.Column('transactions_cursor', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plaid_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plaid_items_item_id'), ['item_id'], unique=True)

    op.create_table('securities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plaid_security_id', sa.String(), nullable=False),
    sa.Column('ticker_symbol', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('close_price_as_of', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('securities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_securities_plaid_security_id'), ['plaid_security_id'], unique=True)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plaid_item_id', sa.Integer(), nullable=False),
    sa.Column('plaid_account_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('official_name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('subtype', sa.String(), nullable=True),
    sa.Column('current_balance', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['plaid_item_id'], ['plaid_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_plaid_account_id'), ['plaid_account_id'], unique=True)

    op.create_table('balance_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'date', name='uq_snapshot_account_date')
    )
    with op.batch_alter_table('balance_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balance_snapshots_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_balance_snapshots_date'), ['date'], unique=False)

    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('institution_price', sa.Float(), nullable=True),
    sa.Column('institution_value', sa.Float(), nullable=True),
    sa.Column('cost_basis', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'security_id')
    )
    op.create_table('investment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('plaid_investment_transaction_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('fees', sa.Float(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('subtype', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investment_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investment_transactions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_investment_transactions_plaid_investment_transaction_id'), ['plaid_investment_transaction_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_investment_transactions_type'), ['type'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('plaid_transaction_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('merchant_name', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('plaid_category', sa.String(), nullable=True),
    sa.Column('pending', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_plaid_transaction_id'), ['plaid_transaction_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_plaid_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_category'))

    op.drop_table('transactions')
    with op.batch_alter_table('investment_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investment_transactions_type'))
        batch_op.drop_index(batch_op.f('ix_investment_transactions_plaid_investment_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_investment_transactions_date'))

    op.drop_table('investment_transactions')
    op.drop_table('holdings')
    with op.batch_alter_table('balance_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balance_snapshots_date'))
        batch_op.drop_index(batch_op.f('ix_balance_snapshots_account_id'))

    op.drop_table('balance_snapshots')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_plaid_account_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('securities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_securities_plaid_security_id'))

    op.drop_table('securities')
    with op.batch_alter_table('plaid_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plaid_items_item_id'))

    op.drop_table('plaid_items')
    op.drop_table('goals')
    op.drop_table('categories')
    # ### end Alembic commands ###
